Name: Bishwo Raj Dhami \
Id: 2413996

# SECTION 4 — TO-DO TASKS: Python Exercises

## 4.1 Exercise on Functions

1.   List item
2.   List item


### Task 1 — Unit Converter

In [1]:
def convert_length(value, direction):
    """
    Converts length between meters and feet.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'mf' for meters->feet, 'fm' for feet->meters.

    Returns:
        float: The converted length value.
    """
    if direction == 'mf':
        return value * 3.28084
    elif direction == 'fm':
        return value / 3.28084
    else:
        raise ValueError("Invalid direction. Use 'mf' or 'fm'.")


def convert_weight(value, direction):
    """
    Converts weight between kilograms and pounds.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'kl' for kg->lbs, 'lk' for lbs->kg.

    Returns:
        float: The converted weight value.
    """
    if direction == 'kl':
        return value * 2.20462
    elif direction == 'lk':
        return value / 2.20462
    else:
        raise ValueError("Invalid direction. Use 'kl' or 'lk'.")


def convert_volume(value, direction):
    """
    Converts volume between liters and gallons.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'lg' for liters->gallons, 'gl' for gallons->liters.

    Returns:
        float: The converted volume value.
    """
    if direction == 'lg':
        return value * 0.264172
    elif direction == 'gl':
        return value / 0.264172
    else:
        raise ValueError("Invalid direction. Use 'lg' or 'gl'.")


def unit_converter():
    """
    Interactive unit converter for length, weight, and volume.
    Prompts user for conversion type and value, then displays the result.
    Handles invalid input using try-except.

    Returns:
        float or None: The converted result, or None on invalid input.
    """
    print("=== Unit Converter ===")
    print("1. Length  (meters <-> feet)")
    print("2. Weight  (kilograms <-> pounds)")
    print("3. Volume  (liters <-> gallons)")

    try:
        category = input("Choose conversion type (1/2/3): ").strip()

        if category == '1':
            print("  a. Meters to Feet")
            print("  b. Feet to Meters")
            sub = input("Choose direction (a/b): ").strip().lower()
            direction = 'mf' if sub == 'a' else 'fm'
            value = float(input("Enter value: "))
            result = convert_length(value, direction)
            unit_from = 'm' if sub == 'a' else 'ft'
            unit_to   = 'ft' if sub == 'a' else 'm'

        elif category == '2':
            print("  a. Kilograms to Pounds")
            print("  b. Pounds to Kilograms")
            sub = input("Choose direction (a/b): ").strip().lower()
            direction = 'kl' if sub == 'a' else 'lk'
            value = float(input("Enter value: "))
            result = convert_weight(value, direction)
            unit_from = 'kg' if sub == 'a' else 'lbs'
            unit_to   = 'lbs' if sub == 'a' else 'kg'

        elif category == '3':
            print("  a. Liters to Gallons")
            print("  b. Gallons to Liters")
            sub = input("Choose direction (a/b): ").strip().lower()
            direction = 'lg' if sub == 'a' else 'gl'
            value = float(input("Enter value: "))
            result = convert_volume(value, direction)
            unit_from = 'L' if sub == 'a' else 'gal'
            unit_to   = 'gal' if sub == 'a' else 'L'

        else:
            print("Invalid category. Please choose 1, 2, or 3.")
            return None

        print(f"\nResult: {value} {unit_from} = {result:.4f} {unit_to}")
        return result

    except ValueError as e:
        print(f"Error: {e}. Please enter a valid numeric value.")
        return None



unit_converter()

=== Unit Converter ===
1. Length  (meters <-> feet)
2. Weight  (kilograms <-> pounds)
3. Volume  (liters <-> gallons)
Choose conversion type (1/2/3): 2
  a. Kilograms to Pounds
  b. Pounds to Kilograms
Choose direction (a/b): a
Enter value: 10

Result: 10.0 kg = 22.0462 lbs


22.0462

### Task 2 — Mathematical Operations on a List of Numbers

In [2]:
def compute_sum(numbers):
    """
    Computes the sum of a list of numbers.

    Parameters:
        numbers (list of float): Input list of numeric values.

    Returns:
        float: The sum of all elements in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("Cannot compute sum of an empty list.")
    total = 0
    for n in numbers:
        total += n
    return total


def compute_average(numbers):
    """
    Computes the average of a list of numbers.

    Parameters:
        numbers (list of float): Input list of numeric values.

    Returns:
        float: The arithmetic mean of the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("Cannot compute average of an empty list.")
    return compute_sum(numbers) / len(numbers)


def compute_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
        numbers (list of float): Input list of numeric values.

    Returns:
        float: The largest element in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("Cannot find maximum of an empty list.")
    max_val = numbers[0]
    for n in numbers[1:]:
        if n > max_val:
            max_val = n
    return max_val


def compute_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
        numbers (list of float): Input list of numeric values.

    Returns:
        float: The smallest element in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("Cannot find minimum of an empty list.")
    min_val = numbers[0]
    for n in numbers[1:]:
        if n < min_val:
            min_val = n
    return min_val


def math_operations():
    """
    Interactive program to perform mathematical operations on user-provided numbers.
    Handles invalid input and empty lists using try-except.

    Returns:
        float or None: The result of the chosen operation, or None on error.
    """
    print("=== Math Operations ===")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = input("Choose operation (1/2/3/4): ").strip()
        raw = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in raw.split()]

        operations = {
            '1': (compute_sum,     'Sum'),
            '2': (compute_average, 'Average'),
            '3': (compute_maximum, 'Maximum'),
            '4': (compute_minimum, 'Minimum'),
        }

        if choice not in operations:
            print("Invalid choice. Please select 1–4.")
            return None

        func, label = operations[choice]
        result = func(numbers)
        print(f"\n{label}: {result}")
        return result

    except ValueError as e:
        print(f"Error: {e}")
        return None

math_operations()

=== Math Operations ===
1. Sum
2. Average
3. Maximum
4. Minimum
Choose operation (1/2/3/4): 1
Enter numbers separated by spaces: 1 2

Sum: 3.0


3.0

---
## 4.2 Exercise on List Manipulation

In [3]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    """
    Returns a new list containing every other element starting from index 0.

    Parameters:
        lst (list): The input list.

    Returns:
        list: Elements at indices 0, 2, 4, ...
    """
    return lst[::2]


# 2. Slice a Sublist
def get_sublist(lst, start, end):
    """
    Returns a sublist from start index to end index (inclusive).

    Parameters:
        lst (list): The input list.
        start (int): Starting index (0-based).
        end (int): Ending index (inclusive).

    Returns:
        list: The sublist from start to end inclusive.
    """
    return lst[start:end + 1]


# 3. Reverse a List Using Slicing
def reverse_list(lst):
    """
    Returns the input list in reverse order using slicing.

    Parameters:
        lst (list): The input list.

    Returns:
        list: Reversed version of lst.
    """
    return lst[::-1]


# 4. Remove First and Last Elements
def remove_first_last(lst):
    """
    Returns the list without its first and last elements.

    Parameters:
        lst (list): The input list (must have at least 2 elements).

    Returns:
        list: Sublist without the first and last elements.
    """
    return lst[1:-1]


# 5. Get First n Elements
def get_first_n(lst, n):
    """
    Returns the first n elements of a list.

    Parameters:
        lst (list): The input list.
        n (int): Number of elements to extract from the start.

    Returns:
        list: First n elements of lst.
    """
    return lst[:n]


# 6. Extract Last n Elements
def get_last_n(lst, n):
    """
    Returns the last n elements of a list.

    Parameters:
        lst (list): The input list.
        n (int): Number of elements to extract from the end.

    Returns:
        list: Last n elements of lst.
    """
    return lst[-n:]


# 7. Extract Elements in Reverse Order (skip one, start from second-to-last)
def reverse_skip(lst):
    """
    Returns every second element starting from the second-to-last, moving backward.

    Parameters:
        lst (list): The input list.

    Returns:
        list: Every other element from the second-to-last to the start.
    """
    return lst[-2::-2]


lst1 = [1, 2, 3, 4, 5, 6]

print("extract_every_other: ", extract_every_other(lst1))
print("get_sublist: ", get_sublist(lst1, 2, 4))
print("reverse_list: ", reverse_list(lst1))
print("remove_first_last: ", remove_first_last(lst1))
print("get_first_n: ", get_first_n(lst1, 3))
print("get_last_n: ", get_last_n(lst1, 2))
print("reverse_skip: ", reverse_skip(lst1))

extract_every_other:  [1, 3, 5]
get_sublist:  [3, 4, 5]
reverse_list:  [6, 5, 4, 3, 2, 1]
remove_first_last:  [2, 3, 4, 5]
get_first_n:  [1, 2, 3]
get_last_n:  [5, 6]
reverse_skip:  [5, 3, 1]


---
## 4.3 Exercise on Nested Lists

In [4]:
# 1. Flatten a Nested List (one level)
def flatten(lst):
    """
    Flattens a singly-nested list into a single flat list.

    Parameters:
        lst (list of lists): A nested list (one level deep).

    Returns:
        list: A flat list with all elements from inner lists.
    """
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result


# 2. Access Nested Element by Indices
def access_nested_element(lst, indices):
    """
    Retrieves an element from a nested list given a sequence of indices.

    Parameters:
        lst (list): A nested list.
        indices (list of int): A list of indices specifying the path to the element.

    Returns:
        The element found at the specified nested position.
    """
    element = lst
    for idx in indices:
        element = element[idx]
    return element


# 3. Sum of All Elements in a Nested List (any depth)
def sum_nested(lst):
    """
    Recursively computes the sum of all numeric elements in a nested list.

    Parameters:
        lst (list): A nested list of numbers at any depth.

    Returns:
        float: The total sum of all elements.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


# 4. Remove Specific Element from Nested List
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from each inner list.

    Parameters:
        lst (list of lists): A nested list.
        elem: The element to remove from every inner list.

    Returns:
        list: The nested list with all occurrences of elem removed.
    """
    return [[x for x in sublist if x != elem] for sublist in lst]


# 5. Find Maximum Element in a Nested List (any depth)
def find_max(lst):
    """
    Recursively finds the maximum element in a nested list.

    Parameters:
        lst (list): A nested list of numbers at any depth.

    Returns:
        float: The maximum numeric value found.
    """
    max_val = None
    for item in lst:
        if isinstance(item, list):
            candidate = find_max(item)
        else:
            candidate = item
        if max_val is None or candidate > max_val:
            max_val = candidate
    return max_val


# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
        lst (list): A nested list.
        elem: The element to count.

    Returns:
        int: The total number of occurrences of elem.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


# 7. Deep Flatten (any depth)
def deep_flatten(lst):
    """
    Recursively flattens a deeply nested list into a single flat list.

    Parameters:
        lst (list): A nested list of arbitrary depth.

    Returns:
        list: A completely flat list containing all elements.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


# 8. Average of All Elements in a Nested List
def average_nested(lst):
    """
    Computes the average of all elements in a nested list.

    Parameters:
        lst (list): A nested list of numbers.

    Returns:
        float: The arithmetic mean of all elements.
    """
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)



print("flatten ([[1,2],[3,4],[5]]) :", flatten([[1, 2], [3, 4], [5]]))

nested_3x3 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("access_nested_element ([[1,2,3],[4,5,6],[7,8,9]], [1,2]) : ", access_nested_element(nested_3x3, [1, 2]))
print("")
print("sum_nested ([[1,2],[3,[4,5]],6]) : ", sum_nested([[1, 2], [3, [4, 5]], 6]))
print("")
print("remove_element ([[1,2],[3,2],[4,5]], 2) : ", remove_element([[1, 2], [3, 2], [4, 5]], 2))
print("")
print("find_max ([[1,2],[3,[4,5]],6]) : ", find_max([[1, 2], [3, [4, 5]], 6]))
print("")
print("count_occurrences([[1,2],[2,3],[2,4]], 2): ", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("")
print("deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]): ", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print("")
print("average_nested([[1,2],[3,4],[5,6]]): ", average_nested([[1, 2], [3, 4], [5, 6]]))

flatten ([[1,2],[3,4],[5]]) : [1, 2, 3, 4, 5]
access_nested_element ([[1,2,3],[4,5,6],[7,8,9]], [1,2]) :  6

sum_nested ([[1,2],[3,[4,5]],6]) :  21

remove_element ([[1,2],[3,2],[4,5]], 2) :  [[1], [3], [4, 5]]

find_max ([[1,2],[3,[4,5]],6]) :  6

count_occurrences([[1,2],[2,3],[2,4]], 2):  3

deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]):  [1, 2, 3, 4, 5, 6, 7, 8]

average_nested([[1,2],[3,4],[5,6]]):  3.5


---
# SECTION 10 — TO-DO NUMPY
## 10.1 Basic Vector and Matrix Operations with NumPy

In [5]:
import numpy as np

### Problem 1 — Array Creation

In [6]:
# 1. Empty array of size 2x2
empty_2x2 = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_2x2)

# 2. All-ones array of size 4x2
ones_4x2 = np.ones((4, 2))
print("\n2. Ones 4x2 array:\n", ones_4x2)

# 3. Array filled with a specific fill value
fill_value = 7
filled_arr = np.full((3, 3), fill_value)
print(f"\n3. Array filled with {fill_value} (3x3):\n", filled_arr)

# 4. Zeros with same shape as an existing array
reference_arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(reference_arr)
print("\n4. Zeros like reference_arr (2x3):\n", zeros_like_arr)

# 5. Ones with same shape as an existing array
ones_like_arr = np.ones_like(reference_arr)
print("\n5. Ones like reference_arr (2x3):\n", ones_like_arr)

# 6. Convert a Python list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_from_list = np.array(new_list)
print("\n6. NumPy array from list [1,2,3,4]:", numpy_from_list)

1. Empty 2x2 array:
 [[7.42169603e-316 0.00000000e+000]
 [5.78741383e-317 5.78741383e-317]]

2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like reference_arr (2x3):
 [[0 0 0]
 [0 0 0]]

5. Ones like reference_arr (2x3):
 [[1 1 1]
 [1 1 1]]

6. NumPy array from list [1,2,3,4]: [1 2 3 4]


### Problem 2 — Array Manipulation: Numerical Ranges and Indexing

In [7]:
# 1. Array with values ranging from 10 to 49
arr_10_49 = np.arange(10, 50)
print("1. arange(10, 50):\n", arr_10_49)

# 2. 3x3 matrix with values 0 to 8
mat_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0–8):\n", mat_3x3)

# 3. 3x3 identity matrix
identity = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity)

# 4. Random array of size 30 and its mean
rand_arr30 = np.random.random(30)
print("\n4. Random array (30 elements):\n", rand_arr30)
print("   Mean:", rand_arr30.mean())

# 5. 10x10 random array – min and max
rand_10x10 = np.random.random((10, 10))
print("\n5. 10x10 random array — Min:", rand_10x10.min(), "| Max:", rand_10x10.max())

# 6. Zero array of size 10, replace 5th element (index 4) with 1
zero_arr10 = np.zeros(10)
zero_arr10[4] = 1
print("\n6. Zero array with 5th element set to 1:\n", zero_arr10)

# 7. Reverse an array
arr_to_reverse = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr_to_reverse[::-1]
print("\n7. Reversed array:", reversed_arr)

# 8. 2D array with 1 on border and 0 inside
border_arr = np.ones((6, 6))
border_arr[1:-1, 1:-1] = 0
print("\n8. Border array (6x6):\n", border_arr)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1   # odd rows, even cols
checkerboard[::2, 1::2] = 1   # even rows, odd cols
print("\n9. 8x8 Checkerboard:\n", checkerboard)

1. arange(10, 50):
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0–8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (30 elements):
 [0.99398475 0.16543801 0.34292607 0.2253993  0.0402747  0.74040953
 0.56677688 0.88368113 0.14441512 0.31812235 0.69331987 0.01479079
 0.4594499  0.8422865  0.65308637 0.47502074 0.39361205 0.03467609
 0.70392972 0.05890373 0.22625734 0.94121359 0.65848494 0.31430719
 0.74617915 0.96876645 0.98728483 0.31184327 0.48920913 0.9568363 ]
   Mean: 0.5116961941970103

5. 10x10 random array — Min: 0.0018826467424326587 | Max: 0.9961055607840329

6. Zero array with 5th element set to 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. Border array (6x6):
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]

9. 8x8

### Problem 3 — Array Operations

In [8]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add two arrays
print("1. x + y =\n", x + y)

# 2. Subtract two arrays
print("\n2. x - y =\n", x - y)

# 3. Multiply array with an integer
scalar = 3
print(f"\n3. x * {scalar} =\n", x * scalar)

# 4. Square of each element
print("\n4. x squared (element-wise) =\n", np.square(x))

# 5. Dot products
print("\n5a. Dot product v · w       =", np.dot(v, w))
print("5b. Dot product x · v       =", np.dot(x, v))
print("5c. Dot product x · y =\n",      np.dot(x, y))

# 6. Concatenate x and y along rows (axis=0), and v and w along columns
concat_xy_rows = np.concatenate((x, y), axis=0)   # vstack equivalent
concat_vw_col  = np.column_stack((v, w))           # side by side as columns
print("\n6a. Concatenate x & y along rows (axis=0):\n", concat_xy_rows)
print("6b. Concatenate v & w as columns:\n",            concat_vw_col)

# 7. Attempt to concatenate x and v
print("\n7. Attempting np.concatenate((x, v)) :")
try:
    result = np.concatenate((x, v))
    print(result)
except ValueError as e:
    print(f"   Error: {e}")
    print("""
   Explanation:
   x has shape (2, 2) — a 2D array.
   v has shape (2,)   — a 1D array.
   np.concatenate requires all arrays to have the SAME number of dimensions.
   Since x is 2D and v is 1D, NumPy cannot concatenate them directly.
""")

1. x + y =
 [[ 6  8]
 [10 13]]

2. x - y =
 [[-4 -4]
 [-4 -3]]

3. x * 3 =
 [[ 3  6]
 [ 9 15]]

4. x squared (element-wise) =
 [[ 1  4]
 [ 9 25]]

5a. Dot product v · w       = 219
5b. Dot product x · v       = [29 77]
5c. Dot product x · y =
 [[19 22]
 [50 58]]

6a. Concatenate x & y along rows (axis=0):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenate v & w as columns:
 [[ 9 11]
 [10 12]]

7. Attempting np.concatenate((x, v)) :
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

   Explanation:
   x has shape (2, 2) — a 2D array.
   v has shape (2,)   — a 1D array.
   np.concatenate requires all arrays to have the SAME number of dimensions.
   Since x is 2D and v is 1D, NumPy cannot concatenate them directly.



### Problem 4 — Matrix Operations

In [9]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


# 1. Prove A · A^-1 = I
A_inv = np.linalg.inv(A)
A_times_Ainv = np.round(np.dot(A, A_inv))   # round to remove floating-point noise
print("1. A · A^-1 (should be Identity):\n", A_times_Ainv)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB =\n", AB)
print("   BA =\n", BA)
print("   AB == BA?", np.array_equal(AB, BA))   # Should be False

# 3. Prove (AB)T = BT AT
LHS = np.dot(A, B).T
RHS = np.dot(B.T, A.T)
print("\n3. (AB)T =\n", LHS)
print("   BT AT  =\n", RHS)
print("   Equal?", np.array_equal(LHS, RHS))    # Should be True

1. A · A^-1 (should be Identity):
 [[1. 0.]
 [0. 1.]]

2. AB =
 [[23 13]
 [51 29]]
   BA =
 [[36 44]
 [13 16]]
   AB == BA? False

3. (AB)T =
 [[23 51]
 [13 29]]
   BT AT  =
 [[23 51]
 [13 29]]
   Equal? True


In [10]:

#  2x - 3y +  z = -1
#   x -  y + 2z = -3
#  3x +  y -  z =  9
#
# Matrix form: AX = B

A_sys = np.array([
    [2, -3,  1],
    [1, -1,  2],
    [3,  1, -1]
], dtype=float)

B_sys = np.array([-1, -3, 9], dtype=float)

# Method 1: Inverse Method  →  X = A^-1B
A_sys_inv = np.linalg.inv(A_sys)
X_inv_method = np.dot(A_sys_inv, B_sys)
print("Solving  2x - 3y + z = -1")
print("          x -  y + 2z = -3")
print("         3x +  y -  z =  9")
print("\nMethod 1 — Inverse Method (X = A^-1B):")
print(f"  x = {X_inv_method[0]:.4f}")
print(f"  y = {X_inv_method[1]:.4f}")
print(f"  z = {X_inv_method[2]:.4f}")

# Method 2: np.linalg.solve  →  more numerically stable
X_solve = np.linalg.solve(A_sys, B_sys)
print("\nMethod 2 — np.linalg.solve():")
print(f"  x = {X_solve[0]:.4f}")
print(f"  y = {X_solve[1]:.4f}")
print(f"  z = {X_solve[2]:.4f}")

# Verify: A · X should equal B
print("\nVerification — A @ X:", np.round(np.dot(A_sys, X_solve), 6))
print("Should equal B:      ", B_sys)

Solving  2x - 3y + z = -1
          x -  y + 2z = -3
         3x +  y -  z =  9

Method 1 — Inverse Method (X = A^-1B):
  x = 2.0000
  y = 1.0000
  z = -2.0000

Method 2 — np.linalg.solve():
  x = 2.0000
  y = 1.0000
  z = -2.0000

Verification — A @ X: [-1. -3.  9.]
Should equal B:       [-1. -3.  9.]


---
## 10.2 Experiment — How Fast is NumPy?

In [11]:
import time
import numpy as np

SIZE = 1_000_000

# Prepare data
list_a = list(range(SIZE))
list_b = list(range(SIZE))
np_a   = np.arange(SIZE, dtype=float)
np_b   = np.arange(SIZE, dtype=float)


# 1. Element-wise Addition
t0 = time.time()
result_list = [list_a[i] + list_b[i] for i in range(SIZE)]
t_list_add = time.time() - t0

t0 = time.time()
result_np = np_a + np_b
t_np_add = time.time() - t0

print("=" * 55)
print(f"1. Element-wise Addition")
print(f"   Python list : {t_list_add:.5f} s")
print(f"   NumPy array : {t_np_add:.5f} s")
print(f"   Speedup     : {t_list_add / t_np_add:.1f}x")


# 2. Element-wise Multiplication
t0 = time.time()
result_list = [list_a[i] * list_b[i] for i in range(SIZE)]
t_list_mul = time.time() - t0

t0 = time.time()
result_np = np_a * np_b
t_np_mul = time.time() - t0

print(f"\n2. Element-wise Multiplication")
print(f"   Python list : {t_list_mul:.5f} s")
print(f"   NumPy array : {t_np_mul:.5f} s")
print(f"   Speedup     : {t_list_mul / t_np_mul:.1f}x")


#  3. Dot Product
t0 = time.time()
dot_list = sum(list_a[i] * list_b[i] for i in range(SIZE))
t_list_dot = time.time() - t0

t0 = time.time()
dot_np = np.dot(np_a, np_b)
t_np_dot = time.time() - t0

print(f"\n3. Dot Product")
print(f"   Python list : {t_list_dot:.5f} s")
print(f"   NumPy array : {t_np_dot:.5f} s")
print(f"   Speedup     : {t_list_dot / t_np_dot:.1f}x")


# 4. Matrix Multiplication (1000x1000)
MAT_SIZE = 1000

# Python list matrix multiplication (naive O(n³))
mat_a = [[float(i * MAT_SIZE + j) for j in range(MAT_SIZE)] for i in range(MAT_SIZE)]
mat_b = [[float(i * MAT_SIZE + j) for j in range(MAT_SIZE)] for i in range(MAT_SIZE)]

print(f"\n4. Matrix Multiplication ({MAT_SIZE}x{MAT_SIZE})")
print("   Running Python list matrix multiplication (this may take a moment)...")

t0 = time.time()
# Transpose mat_b once to speed up column access
mat_b_T = [[mat_b[j][i] for j in range(MAT_SIZE)] for i in range(MAT_SIZE)]
result_mat = [
    [sum(mat_a[r][k] * mat_b_T[c][k] for k in range(MAT_SIZE)) for c in range(MAT_SIZE)]
    for r in range(MAT_SIZE)
]
t_list_mat = time.time() - t0

np_mat_a = np.array(mat_a)
np_mat_b = np.array(mat_b)
t0 = time.time()
result_np_mat = np_mat_a @ np_mat_b
t_np_mat = time.time() - t0

print(f"   Python list : {t_list_mat:.5f} s")
print(f"   NumPy array : {t_np_mat:.5f} s")
print(f"   Speedup     : {t_list_mat / t_np_mat:.1f}x")
print("=" * 55)
print("Conclusion: NumPy is dramatically faster for numerical")
print("operations, especially as array size increases, because")
print("it uses optimised C/Fortran code under the hood.")

1. Element-wise Addition
   Python list : 0.13304 s
   NumPy array : 0.00750 s
   Speedup     : 17.7x

2. Element-wise Multiplication
   Python list : 0.15875 s
   NumPy array : 0.00661 s
   Speedup     : 24.0x

3. Dot Product
   Python list : 0.11372 s
   NumPy array : 0.00383 s
   Speedup     : 29.7x

4. Matrix Multiplication (1000x1000)
   Running Python list matrix multiplication (this may take a moment)...
   Python list : 175.88240 s
   NumPy array : 0.06485 s
   Speedup     : 2712.0x
Conclusion: NumPy is dramatically faster for numerical
operations, especially as array size increases, because
it uses optimised C/Fortran code under the hood.
